In [3]:
import numpy as np

In [6]:
x= np.array([1,2,3,4])

In [7]:
type(x)

numpy.ndarray

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros([3,4])  # 3 satir 4 sutun 0'lardan olusan array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones([2,4])*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [14]:
np.arange(10,60,10)

array([10, 20, 30, 40, 50])

In [17]:
ondalik=np.arange(0,2,0.5)
ondalik

array([0. , 0.5, 1. , 1.5])

In [19]:
lin= np.linspace(0,4,12) #0'dan 4'e kadar 12 tane sayidan olusan array
lin

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

In [21]:
rand = np.random.rand(3,4)   #3 satir 4 sutun rastgele sayidan olusan 0-1 arasi degerler
rand

array([[0.17313933, 0.50813927, 0.53190315, 0.69147526],
       [0.88922742, 0.06607892, 0.45081899, 0.70214861],
       [0.79951321, 0.39283496, 0.20330874, 0.78168094]])

In [22]:
rand2 = np.random.randn(3,4)  #normal dagilim ile
rand2

array([[-0.66878418,  0.84345416,  2.20571057, -0.88604041],
       [-0.74735106, -0.45035504, -1.07998188,  0.06362139],
       [ 0.98571836, -1.38615872, -0.28292468, -0.95756423]])

In [23]:
z= rand2*5
z

array([[-3.34392089,  4.21727082, 11.02855287, -4.43020204],
       [-3.73675531, -2.25177519, -5.39990942,  0.31810696],
       [ 4.92859182, -6.93079362, -1.41462338, -4.78782116]])

In [24]:
np.eye(5)  #5 satir 5 sutunlu birim matris

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.randint(1,50,15)  #rastgele integer sayilar

array([ 6,  6, 36,  8, 27, 38,  5, 40,  7, 41, 23, 45, 11,  6, 27])

In [27]:
s=np.arange(24)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
s.reshape(6,4)  # tek boyutlu olan s array'ini reshape ile 6 satir 4 sutun haline getirebiliriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
s.reshape(2,3,4)  #3 boyutlu hale getirme. 2 tane 3 satirli 4 sutunlu array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
c=np.random.randint(1,50,20)

In [33]:
c.max()

49

In [34]:
c.min()

1

In [35]:
c.argmax()  #maksimum sayinin indeksi

16

In [36]:
c.argmin()

2

In [42]:
b=np.arange(50)  #50'ye kadar olan sayilar
b.shape=2,-1,5   #b'yi tekrar düzenlemek, 2 satirli -1:araya en uygun neyse onu yap
b.shape          # aradaki en uygun sayi 5'mis

(2, 5, 5)

In [43]:
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])