# NUMPY INDEKSLEME

In [1]:
import numpy as np

# Tek Boyutlu Array

In [2]:
a=np.arange(10)**2

In [3]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [4]:
a[3]  #3 indesli 4.eleman

9

In [6]:
a[3:6]   #3. indeksdeki eleman dahil (yani 4. eleman) ama 6.indeksteki eleman dahil değil(yani 7.eleman)

array([ 9, 16, 25], dtype=int32)

In [7]:
a[4]=100 #4.indeksteki elemana 100 atadik

In [8]:
a

array([  0,   1,   4,   9, 100,  25,  36,  49,  64,  81], dtype=int32)

In [9]:
for i in a:
    print(i**2)

0
1
16
81
10000
625
1296
2401
4096
6561


# Çok Boyutlu Array

In [10]:
ar1= np.random.random(16)

In [11]:
ar1

array([0.043381  , 0.77458389, 0.55092035, 0.56341114, 0.71672301,
       0.65506357, 0.7056203 , 0.70805318, 0.40975414, 0.38224509,
       0.37608822, 0.38645523, 0.73358886, 0.09057259, 0.07879202,
       0.9808967 ])

In [13]:
ar1=ar1.reshape(4,4)
ar1

array([[0.043381  , 0.77458389, 0.55092035, 0.56341114],
       [0.71672301, 0.65506357, 0.7056203 , 0.70805318],
       [0.40975414, 0.38224509, 0.37608822, 0.38645523],
       [0.73358886, 0.09057259, 0.07879202, 0.9808967 ]])

In [14]:
ar1.ravel() #reshape ile cok boyutlu hale getirdigimiz array'i eski haline getirme

array([0.043381  , 0.77458389, 0.55092035, 0.56341114, 0.71672301,
       0.65506357, 0.7056203 , 0.70805318, 0.40975414, 0.38224509,
       0.37608822, 0.38645523, 0.73358886, 0.09057259, 0.07879202,
       0.9808967 ])

In [15]:
ar1[0:2,1]

array([0.77458389, 0.65506357])

In [17]:
ar1[:,3]   #son sutunu aldi

array([0.56341114, 0.70805318, 0.38645523, 0.9808967 ])

In [18]:
for satir in ar1:
    print(satir)

[0.043381   0.77458389 0.55092035 0.56341114]
[0.71672301 0.65506357 0.7056203  0.70805318]
[0.40975414 0.38224509 0.37608822 0.38645523]
[0.73358886 0.09057259 0.07879202 0.9808967 ]


In [20]:
for satir in ar1.flat:      #flat ile bütün satırlar alt alta yazılmış oldu
    print(satir)

0.04338099622058156
0.7745838866574253
0.5509203544447051
0.5634111403921205
0.7167230091910995
0.6550635655501486
0.7056203012455
0.7080531777278053
0.4097541420925578
0.38224509000304285
0.3760882157021589
0.3864552316847141
0.7335888643769252
0.09057259322886935
0.07879201560687177
0.9808966997903564


In [22]:
for i in np.ndenumerate(ar1):   #ndenumerate ile satır sutun numaraları ile sıralama
    print(i)

((0, 0), 0.04338099622058156)
((0, 1), 0.7745838866574253)
((0, 2), 0.5509203544447051)
((0, 3), 0.5634111403921205)
((1, 0), 0.7167230091910995)
((1, 1), 0.6550635655501486)
((1, 2), 0.7056203012455)
((1, 3), 0.7080531777278053)
((2, 0), 0.4097541420925578)
((2, 1), 0.38224509000304285)
((2, 2), 0.3760882157021589)
((2, 3), 0.3864552316847141)
((3, 0), 0.7335888643769252)
((3, 1), 0.09057259322886935)
((3, 2), 0.07879201560687177)
((3, 3), 0.9808966997903564)


In [24]:
a=np.array([2,3])
b=np.array([5,6])

In [27]:
np.hstack((a,b))   #iki stack'i horizontal (yatay) olarak birlestirme

array([2, 3, 5, 6])

In [28]:
np.vstack((a,b))

array([[2, 3],
       [5, 6]])

In [32]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6]])   #aynı boyutta olması için [[]] şeklinde yazdık

In [33]:
np.concatenate((c,d),axis=0)  #axis=0 dedigimizde alt alta birleştiriyor

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.concatenate((c,d),axis=1)  #axis=1 dedigimizde yanyana birleştiriyor

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [36]:
np.concatenate((c,d.T),axis=1)  #yukarıda hata aldık. Transpozunu almak gerekli

array([[1, 2, 5],
       [3, 4, 6]])